config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    root to: 'homes#top'
    get 'homes/about' => 'homes#about'
    resources :customers, only: [:show, :edit, :update] do
      get 'confirm'
      patch 'leave'
    end
    resources :products, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy] do
      delete 'cart_items' => 'cart_items#destroy_all', as: "destroy"
    end
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm'
        get 'complete'
      end
    end
    resources :deliveries, only: [:index, :create, :destroy, :edit, :update]
  end

  namespace :admin do
    root to: 'homes#top'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :products, only: [:index, :new, :create, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    resources :genres, only: [:index, :create, :edit, :update]
  end

  devise_for :customers, controllers: {
  registrations: 'public/registrations',
  sessions: 'public/sessions'
}

  devise_for :admins, controllers: {
  sessions: 'admin/sessions'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :product
  
  validates :quantity, :customer_id, :product_id, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :deliveries, dependent: :destroy
  
  validates :last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :residence, :phone_number, :email, presence: true
  
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  belongs_to :customer

  def full_address
    self.postcode + " " + self.address + " " + self.name
  end
  
  validates :name, presence: true
  validates :postcode, presence: true
  validates :address, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :products
  validates :name, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { wait: 0, confirm: 1, making: 2, prepare: 3, finish: 4 }

  belongs_to :customer, optional: true
  has_many :order_details, dependent: :destroy
  has_many :products, through: :order_details

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  enum making_status: { impossible: 0, wait: 1, making: 2, complete: 3 }

  belongs_to :product
  belongs_to :order
  
end

app/models/product.rb
class Product < ApplicationRecord
  enum is_sale_active: { 販売中: true, 販売停止中: false }
  has_many :cart_items
  has_many :order_details
  belongs_to :genre
  attachment :image
  def add_tax_tax_out_price
    (self.tax_out_price * 1.10).round
  end
  validates :image, presence: true
  validates :name, presence: true
  validates :introduction, presence: true
  validates :genre_id, presence: true
  validates :tax_out_price, presence: true
  validates :is_sale_active, inclusion: [true, false]
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customer = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    customer = Customer.find(params[:id])
    customer.update(customer_params)
    redirect_to admin_customer_path(customer)
  end

  private
  def customer_params
    params.require(:customer).permit(
      :email,
      :password,
      :first_name,
      :last_name,
      :first_name_kana,
      :last_name_kana,
      :is_active,
      :residence,
      :postcode,
      :address,
      :phone_number)
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      redirect_to admin_genres_path
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genres = Genre.all
    @genre.update(genre_params)
      redirect_to admin_genres_path
  end
  
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    @order = Order.all
    @order = Order.page(params[:page]).per(10)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def update
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @order.update(order_params)
    if params[:order][:status] == "wait"
      @order_details.update_all(making_status: 0)
    elsif params[:order][:status] == "confirm"
      @order_details.update_all(making_status: 1)
    end
    redirect_to admin_order_path(@order)
  end
  
  private

  def order_params
  	params.require(:order).permit(:status)
  end
  
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    product = Product.new(product_params)
    product.save
    redirect_to admin_product_path(product.id)
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    product = Product.find(params[:id])
    product.update(product_params)
    redirect_to admin_product_path(product)
  end

  private
  def product_params
    params.require(:product).permit(
    :genre_id,
    :name,
    :introduction,
    :tax_out_price,
    :image,
    :is_sale_active)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_name_kana, :last_name_kana, :postcode, :residence, :phone_number, :is_active])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5 mypage-title">
      <h2 class"customer-name"><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h2>
    </div>
      <div class="col-md-9"></div>
  </div>
  <div class="row">
    <div class="col-md-10">
    <%= form_with model: @customer, url: admin_customer_path, local: true do |f| %>
    <table class="table table-noborder">
      <tbody>
        <tr>
          <td>顧客ID</td>
          <td><%= @customer.id %></td>
        </tr>

        <tr>
          <td>名前</td>
          <td>
            <div　class="field">
              <%= f.text_field :last_name, placeholder: "令和" %>
            </div>
          </td>
          <td>
            <div　class="field">
              <%= f.text_field :first_name, placeholder: "道子" %>
            </div>
          </td>
        </tr>

        <tr>
          <td>フリガナ</td>
          <td>
            <div class= "field">
              <%= f.text_field :last_name_kana, autofocus: true, placeholder: "レイワ" %>
            </div>
          </td>
          <td>
            <div class="field">
              <%= f.text_field :first_name_kana, autofocus: true, placeholder: "ミチコ" %>
            </div>
          </td>
        </tr>

        <tr>
          <td>メールアドレス</td>
          <td>
            <div class="field">
              <%= f.text_field :email, autofocus: true, placeholder: "sample@example.com" %>
            </div>
          </td>
        </tr>

        <tr>
          <td>郵便番号(ハイフンなし)</td>
          <td>
            <div>
              <%= f.text_field :postcode, autofocus: true, placeholder: "0000000" %>
            </div>
          </td>
        </tr>

        <tr>
          <td>住所</td>
          <td colspan="2">
            <div class="field">
              <%= f.text_field :residence, :size=>"60", autofocus: true, placeholder: "東京都渋谷区代々木神園町0-0" %>
            </div>
          </td>
        </tr>

        <tr>
          <td>電話番号(ハイフンなし)</td>
          <td>
            <div class="field">
              <%= f.text_field :phone_number, autofocus: true, placeholder: "0000000000" %>
            </div>
          </td>
        </tr>

        <tr>
          <td>会員ステータス</td>
          <td>
            <%= f.radio_button :is_active, :true %>
            <%= f.label :is_active, :"有効" %>
            <%= f.radio_button :is_active, :false %>
            <%= f.label :is_active, :"退会" %>
          </td>
        </tr>

        <tr>
          <td></td>
          <td>
            <div class="actions">
              <%= f.submit "編集を保存する", class:"btn btn-success" %>
            </div>
          </td>
        </tr>

      </tbody>
    </table>
    <% end %>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-3">
      <h4 class="mypage-title">会員一覧</h4>
    </div>
    <div class="col-md-8"></div>
  </div>
  <div class="row">
    <div class="col-md-10 offset-md-1">
      <table class="table customer-index-table">
        <thead>
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customer.each do |customer| %>
          <tr>
            <td><%= customer.id %></td>
            <td>
              <%= link_to admin_customer_path(customer.id) do %>
                <%= customer.last_name %>
                <%= customer.first_name %>
              <% end %>
            </td>
            <td><%= customer.email %></td>
            <% if customer.is_active == true %>
              <td>
                <span class="text-success font-weight-bold h5">有効</span>
              </td>
            <% else %>
              <td>
                <span class="text-danger font-weight-bold h5">退会</span>
              </td>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-1">
      <h4 class="mypage-title"><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報詳細</h4>
    </div>
      <div class="col-md-9"></div>
  </div>
  <div class="row">
    <div class="col-md-8">
    <%= form_with model: @customer, url: admin_customer_path, local: true do |f| %>
    <table class="table order-customer-table">
      <tbody>
        <tr>
          <th>会員ID</th>
          <td><%= @customer.id %></td>
        </tr>

        <tr>
          <th>氏名</th>
          <td>
            <%= @customer.last_name %>
            <%= @customer.first_name %>
          </td>
        </tr>

        <tr>
          <th>フリガナ</th>
          <td>
            <%= @customer.last_name_kana %>
            <%= @customer.first_name_kana %>
          </td>
        </tr>

        <tr>
          <th>メールアドレス</th>
          <td>
            <%= @customer.email %>
          </td>
        </tr>

        <tr>
          <th>郵便番号(ハイフンなし)</th>
          <td>
            <div>
              <%= @customer.postcode %>
            </div>
          </td>
        </tr>

        <tr>
          <th>住所</th>
          <td colspan="2">
            <%= @customer.residence %>
          </td>
        </tr>

        <tr>
          <th>電話番号(ハイフンなし)</th>
          <td>
            <div class="field">
              <%= @customer.phone_number %>
            </div>
          </td>
        </tr>

        <tr>
          <th>会員ステータス</th>
          <td>
            <% if @customer.is_active == true %>
              <span class="text-success font-weight-bold">有効</span>
            <% else %>
              <span class="text-danger font-weight-bold">退会</span>
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
            <div class="actions">
              <%= link_to "編集する", edit_admin_customer_path(@customer.id), class:"btn btn-success" %>
              <%= link_to "注文履歴一覧をみる", admin_root_path, class:"btn btn-primary ml-3" %>
            </div>
    <% end %>
  </div>
</div>