config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    root to: 'homes#top'
    get 'homes/about' => 'homes#about'
    resources :customers, only: [:show, :edit, :update] do
      get 'confirm'
      patch 'leave'
    end
    resources :products, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy] do
      delete 'cart_items' => 'cart_items#destroy_all', as: "destroy"
    end
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm'
        get 'complete'
      end
    end
    resources :deliveries, only: [:index, :create, :destroy, :edit, :update]
  end

  namespace :admin do
    root to: 'homes#top'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :products, only: [:index, :new, :create, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    resources :genres, only: [:index, :create, :edit, :update]
  end

  devise_for :customers, controllers: {
  registrations: 'public/registrations',
  sessions: 'public/sessions'
}

  devise_for :admins, controllers: {
  sessions: 'admin/sessions'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :product
  
  validates :quantity, :customer_id, :product_id, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :deliveries, dependent: :destroy
  
  validates :last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :residence, :phone_number, :email, presence: true
  
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  belongs_to :customer

  def full_address
    self.postcode + " " + self.address + " " + self.name
  end
  
  validates :name, presence: true
  validates :postcode, presence: true
  validates :address, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :products
  validates :name, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { wait: 0, confirm: 1, making: 2, prepare: 3, finish: 4 }

  belongs_to :customer, optional: true
  has_many :order_details, dependent: :destroy
  has_many :products, through: :order_details

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  enum making_status: { impossible: 0, wait: 1, making: 2, complete: 3 }

  belongs_to :product
  belongs_to :order
  
end

app/models/product.rb
class Product < ApplicationRecord
  enum is_sale_active: { 販売中: true, 販売停止中: false }
  has_many :cart_items
  has_many :order_details
  belongs_to :genre
  attachment :image
  def add_tax_tax_out_price
    (self.tax_out_price * 1.10).round
  end
  validates :image, presence: true
  validates :name, presence: true
  validates :introduction, presence: true
  validates :genre_id, presence: true
  validates :tax_out_price, presence: true
  validates :is_sale_active, inclusion: [true, false]
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      redirect_to admin_genres_path
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genres = Genre.all
    @genre.update(genre_params)
      redirect_to admin_genres_path
  end
  
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    @order = Order.all
    @order = Order.page(params[:page]).per(10)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def update
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @order.update(order_params)
    if params[:order][:status] == "wait"
      @order_details.update_all(making_status: 0)
    elsif params[:order][:status] == "confirm"
      @order_details.update_all(making_status: 1)
    end
    redirect_to admin_order_path(@order)
  end
  
  private

  def order_params
  	params.require(:order).permit(:status)
  end
  
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    product = Product.new(product_params)
    product.save
    redirect_to admin_product_path(product.id)
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    product = Product.find(params[:id])
    product.update(product_params)
    redirect_to admin_product_path(product)
  end

  private
  def product_params
    params.require(:product).permit(
    :genre_id,
    :name,
    :introduction,
    :tax_out_price,
    :image,
    :is_sale_active)
  end

end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  
  private
  def after_sign_in_path_for(resource)
    admin_root_path
  end

  def after_sign_out_path_for(resource)
    admin_session_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_name_kana, :last_name_kana, :postcode, :residence, :phone_number, :is_active])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/_form.html.erb
<%= form_with model:@genre, url:admin_genres_path local:true do |f| %>
  <form class="form-inline">
    <div class="form-group">
      <%= f.label :name, "ジャンル名" %>
      <%= f.text_field :name %>
    </div>
    <div class="form-group">
      <%= f.submit class: 'bnt btn-success' %>
    </div>
  </form>
<% end %>

app/views/admin/genres/create.html.erb
<h1>Admin::Genres#create</h1>
<p>Find me in app/views/admin/genres/create.html.erb</p>

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h4 class="mypage-title">ジャンル編集</h4>
        <%= form_with model:@genre, url:admin_genre_path(@genre.id), local:true do |f| %>
          <div class="row">
            <div class="form-group">
                <%= f.label :name, "ジャンル名", class:"admin-genre-name" %>
                <%= f.text_field :name %>
            </div>
            <div class="form-group">
                <%= f.submit "変更を保存", class: 'bnt btn-success' %>
            </div>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h4 class="mypage-title">ジャンル一覧・追加</h4>
          <%= form_with model:@genre, url:admin_genres_path, local:true do |f| %>
            <%= f.label :name, "ジャンル名" %>
            <%= f.text_field :name, placeholder:"ジャンル名"  %>
            <%= f.submit "新規登録", class: 'bnt btn-success' %>
          <% end %>
      <div class="genre-table">
        <table class="table table-hover customer-index-table">
          <thead>
            <tr class="active">
              <th>ジャンル</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @genres.each do |genre| %>
              <tr>
                <td><%= genre.name %></td>
                <td><%= link_to '編集する', edit_admin_genre_path(genre), class: 'bnt btn-success' %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/genres/update.html.erb
<h1>Admin::Genres#update</h1>
<p>Find me in app/views/admin/genres/update.html.erb</p>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-3">
      <h5 class="mypage-title">注文履歴詳細</h5>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-10">
      <table class="table order-customer-table">
        <tr>
          <th>購入者</th>
          <td>
            <%= link_to admin_customer_path(@order.customer) do %>
            <%= @order.customer.last_name %>  <%= @order.customer.first_name %>
            <% end %>
          </td>
        </tr>
        <tr>
          <th>注文日</th>
          <td><%= @order.customer.created_at.strftime("%Y/%m/%d") %></td>
        </tr>
        <tr>
          <th>配送先</th>
          <td>〒<%= @order.customer.postcode %> <%= @order.customer.residence %><br>
          <%= @order.customer.last_name %><%= @order.customer.first_name %></td>
        </tr>
        <tr>
          <th>支払方法</th>
          <td><%= @order.payment_method_i18n %></td>
        </tr>
        <tr>
          <th>注文ステータス</th>
          <td>
            <%= form_with model:@order, url:admin_order_path(@order) do |f| %>
            <%= f.select :status, Order.statuses_i18n.invert %>
            <%= f.submit "更新", class: "btn btn-success" %>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-md-9">
      <table class="table table-hover customer-index-table">
        <thead>
          <tr>
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @order_details.each do |order_detail| %>
          <tr>
            <td><%= order_detail.product.name %></td>
            <td><%= (order_detail.tax_in_price).to_s(:delimited) %></td>
            <td><%= order_detail.order_quantity %></td>
            <td><%= (order_detail.tax_in_price * order_detail.order_quantity).to_s(:delimited) %></td>
            <td>
              <%= form_with model:order_detail, url:admin_order_detail_path(order_detail) do |f| %>
              <%= f.select :making_status, OrderDetail.making_statuses_i18n.invert %>
              <%= f.submit "更新", class: "btn btn-success" %>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-md-3 d-flex align-items-end">
      <table>
        <tr>
          <td>商品合計</td>
          <td><%= (@order.total_price - @order.postage).to_s(:delimited) %>円</td>
        </tr>
        <tr>
          <td>送料</td>
          <td><%= @order.postage.to_s(:delimited) %>円</td>
        </tr>
        <tr>
          <td>請求金額合計</td>
          <td><%= @order.total_price.to_s(:delimited) %>円</td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/admin/orders/update.html.erb
<h1>Admin::Orders#update</h1>
<p>Find me in app/views/admin/orders/update.html.erb</p>

app/views/admin/products/create.html.erb
<h1>Admin::Products#create</h1>
<p>Find me in app/views/admin/products/create.html.erb</p>

app/views/admin/products/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h4 class="customer-new">商品新規登録</h4>
    </div>
    <div class="col-md-9"></div>
  </div>
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-10">
        <%= form_with model: @product, url: admin_product_path, local: true do |f| %>
          <table class="table table-noborder">
            <tbody>
              <tr>
                <td>商品画像</td>
                <td>
                  <div class="img_field">
                    <%= f.attachment_field :image, class:"form-control-file user_image",class:"ml-5"  %>
                  </div>
                </td>
              </tr>
              <tr>
                <td>商品名</td>
                <td>
                  <div class="field">
                    <%= f.text_field :name, :size=>"30", autofocus: true, placeholder: "商品名",class:"ml-5" %>
                  </div>
                </td>
              </tr>
              <tr>
                <td>商品説明</td>
                <td>
                  <div class="field">
                    <%= f.text_area :introduction, :size=>"28", autofocus: true, placeholder: "ここに説明文を記述します", class:"ml-5" %>
                  </div>
                </td>
              </tr>
              <tr>
                <td>ジャンル</td>
                <td>
                  <div class="field admin-products-edit-genre">
                    <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "--選択して下さい--", class:"ml-5"  %>
                  </div>
                </td>
              </tr>
              <tr>
                <td>税抜価格</td>
                <td colspan="2">
                <div class="field">
                    <%= f.text_field :tax_out_price, :size=>"30", autofocus: true, placeholder: "1000", class:"ml-5" %>円
                </div>
                </td>
              </tr>
              <tr>
                <td>販売ステータス</td>
                <td>
                  <div class="row">
                    <div class="col-md-1"></div>
                    <div class="col-md-7">
                      <%= f.radio_button :is_sale_active, :"販売中" %>
                      <%= f.label :is_sale_active, :"販売中" %>
                      <%= f.radio_button :is_sale_active, :"販売停止中" %>
                      <%= f.label :is_sale_active, :"販売停止中" %>
                    </div>
                    <div class="col-md-4"></div>
                  </div>
                </td>
              </tr>
              <tr>
                <td></td>
                <td>
                  <div class="row">
                    <div class="col-md-1"></div>
                    <div class="col-md-7">
                      <%= f.submit "変更を保存", class:"mx-5  btn btn-success",:size=>"30" %>
                    </div>
                    <div class="col-md-4"></div>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        <% end %>
    </div>
  </div>
</div>

app/views/admin/products/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-3">
      <h4 class="mypage-title">商品一覧</h2>
    </div>
    <div class="col-md-6 plus-icon">
      <%= link_to "＋", new_admin_product_path, class:"btn btn-success rounded-circle" %>
    </div>
    <div class="col-md-2"></div>
  </div>
  <div class="row">
    <div class="col-md-10 offset-md-1">
      <div id="create">
        <table class="table table-hover table-inverse products-index">
          <thead>
            <tr class="info">
              <th>商品ID</th>
              <th>商品名</th>
              <th>税抜価格</th>
              <th>ジャンル</th>
              <th>ステータス</th>
            </tr>
          </thead>
          <tbody>
            <% @products.each do |product| %>
              <tr>
                <td>
                  <%= product.id %>
                </td>
                <td class="text_left">
                  <%= link_to admin_product_path(product.id) do %>
                    <%= product.name %>
                  <% end %>
                </td>
                <td class="text_left">
                  <%= product.tax_out_price.to_s(:delimited) %>
                </td>
                <td>
                  <%= product.genre.name %>
                </td>
                <td class="font-weight-bold h5">
                  <% if product.is_sale_active == true %>
                    <div class="text-success">
                      販売中
                    </div>
                  <% elsif product.is_sale_active == false %>
                    <div class="text-danger">
                      販売停止中
                    </div>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        </div>
      </div
    <div class="col-md-2"></div>
  </div>
</div>

app/views/admin/products/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h4 class="customer-new">商品新規登録</h4>
    </div>
    <div class="col-md-9"></div>
  </div>
  <div class="row">
    <div class="col-md-10 offset-md-1">
      <table class="table table-noborder">
        <%= form_with model: @product, url: admin_products_path, local: true do |f| %>
          <tbody>
            <tr>
              <td>商品画像</td>
              <td>
                <div class="img_field">
                  <%= f.attachment_field :image, class:"form-control-file user_image",class:"ml-5"  %>
                </div>
              </td>
            </tr>
            <tr>
              <td>商品名</td>
              <td>
                <div class="field">
                  <%= f.text_field :name, :size=>"30", autofocus: true, placeholder: "商品名",class:"ml-5" %>
                </div>
              </td>
            </tr>
            <tr>
              <td>商品説明</td>
              <td>
                <div class="field">
                  <%= f.text_area :introduction, :size=>"60", autofocus: true, placeholder: "ここに説明文を記述します", class:"ml-5" %>
                </div>
              </td>
            </tr>
            <tr>
              <td>ジャンル</td>
              <td>
                <div class="field admin-products-edit-genre">
                  <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "--選択して下さい--", class:"ml-5" %>
                </div>
              </td>
            </tr>
            <tr>
              <td>税抜価格</td>
              <td colspan="2">
                <div class="field">
                  <%= f.text_field :tax_out_price, :size=>"30", autofocus: true, placeholder: "1000", class:"ml-5" %>円
                </div>
              </td>
            </tr>
            <tr>
              <td>販売ステータス</td>
              <td>
                <div class="row">
                  <div class="col-md-1"></div>
                  <div class="col-md-7">
                    <%= f.radio_button :is_sale_active, :true %>
                    <%= f.label :is_sale_active, :"販売中" %>
                    <%= f.radio_button :is_sale_active, :false %>
                    <%= f.label :is_sale_active, :"販売停止中" %>
                  </div>
                  <div class="col-md-4"></div>
                </div>
              </td>
            </tr>
            <tr>
              <td></td>
              <td>
                <div class="row">
                  <div class="col-md-1"></div>
                  <div class="col-md-7">
                    <%= f.submit "新規登録", class:"mx-5  btn btn-success",:size=>"30" %>
                  </div>
                  <div class="col-md-4"></div>
                </div>
              </td>
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/products/show.html.erb
<div class="container">
  <div class="row">
    <h4 class="customer-new">商品詳細</h4>
  </div>
  <div class="row">
    <div class="col-md-4">
        <div class="id img-field"><%= attachment_image_tag(@product, :image, :fill, 300, 300, format: 'jpeg', size:"100×100",fallback: "no_image.jpg") %></div>
      </div>
      <div class="col-md-8">
        <table class="table order-customer-table">
          <tbody>
            <tr>
              <th>商品名</th>
              <td><%= @product.name %></td>
            </tr>
            <tr>
              <th>商品説明</th>
              <td><%= @product.introduction %></td>
            </tr>
            <tr>
              <th>ジャンル</th>
              <td><%= @product.genre.name %></td>
            </tr>
            <tr>
              <th>税込価格（税抜価格）</th>
              <td><%= @product.add_tax_tax_out_price.to_s(:delimited) %>(<%= @product.tax_out_price.to_s(:delimited) %>)円</td>
            </tr>
            <tr>
              <th>販売ステータス</th>
              <td class="font-weight-bold h5">
                <% if @product.is_sale_active == true %>
                  <span class="text-success font-weight-bold">販売中</span>
                <% else %>
                  <span class="text-danger font-weight-bold">販売停止中</span>
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>
      <div class="acstions col-md-12">
        <%= link_to "編集する", edit_admin_product_path(@product), data: {"turbolinks" => false}, class: "glyphicon glyphicon-pencil btn btn-success pull-right" %>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/update.html.erb
<h1>Admin::Products#update</h1>
<p>Find me in app/views/admin/products/update.html.erb</p>