config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    root to: 'homes#top'
    get 'homes/about' => 'homes#about'
    resources :customers, only: [:show, :edit, :update] do
      get 'confirm'
      patch 'leave'
    end
    resources :products, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy] do
      delete 'cart_items' => 'cart_items#destroy_all', as: "destroy"
    end
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm'
        get 'complete'
      end
    end
    resources :deliveries, only: [:index, :create, :destroy, :edit, :update]
  end

  namespace :admin do
    root to: 'homes#top'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :products, only: [:index, :new, :create, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    resources :genres, only: [:index, :create, :edit, :update]
  end

  devise_for :customers, controllers: {
  registrations: 'public/registrations',
  sessions: 'public/sessions'
}

  devise_for :admins, controllers: {
  sessions: 'admin/sessions'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :product
  
  validates :quantity, :customer_id, :product_id, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :deliveries, dependent: :destroy
  
  validates :last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :residence, :phone_number, :email, presence: true
  
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  belongs_to :customer

  def full_address
    self.postcode + " " + self.address + " " + self.name
  end
  
  validates :name, presence: true
  validates :postcode, presence: true
  validates :address, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :products
  validates :name, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { wait: 0, confirm: 1, making: 2, prepare: 3, finish: 4 }

  belongs_to :customer, optional: true
  has_many :order_details, dependent: :destroy
  has_many :products, through: :order_details

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  enum making_status: { impossible: 0, wait: 1, making: 2, complete: 3 }

  belongs_to :product
  belongs_to :order
  
end

app/models/product.rb
class Product < ApplicationRecord
  enum is_sale_active: { 販売中: true, 販売停止中: false }
  has_many :cart_items
  has_many :order_details
  belongs_to :genre
  attachment :image
  def add_tax_tax_out_price
    (self.tax_out_price * 1.10).round
  end
  validates :image, presence: true
  validates :name, presence: true
  validates :introduction, presence: true
  validates :genre_id, presence: true
  validates :tax_out_price, presence: true
  validates :is_sale_active, inclusion: [true, false]
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      redirect_to admin_genres_path
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genres = Genre.all
    @genre.update(genre_params)
      redirect_to admin_genres_path
  end
  
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    @order = Order.all
    @order = Order.page(params[:page]).per(10)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_name_kana, :last_name_kana, :postcode, :residence, :phone_number, :is_active])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div>
    <p class="text-center">copy.right</p>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg">
    <div class="container">
      <% if admin_signed_in? %>
        <a class="navbar-brand" href="/admin"><%= image_tag 'nagano-cake-logo.png',size: '300x100' , class: 'logo'%></a>
      <% else %>
        <a class="navbar-brand" href="/public"><%= image_tag 'nagano-cake-logo.png',size: '300x100' , class: 'logo'%></a>
      <% end %>
      <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-collapse collapse" id="navbarNavDropdown" style="">
        <ul class="navbar-nav ml-auto">
          <% if customer_signed_in? %>
            <li>
              <p class="mt-auto mb-auto mr-3">ようこそ、<%= current_customer.first_name %>さん！</p>
            </li>
            <li>
              <%= link_to "マイページ", public_customer_path(current_customer), class: 'btn btn-primary mr-2' %>
            </li>
            <li>
              <%= link_to "商品一覧", public_products_path, class: 'btn btn-primary mr-2' %>
            </li>
            <li>
              <%= link_to "カート", public_cart_items_path, class: 'btn btn-primary mr-2' %>
            </li>
            <li>
              <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'btn btn-primary mr-1' %>
            </li>
          <% elsif admin_signed_in? %>
            <li>
              <%= link_to "商品一覧", admin_products_path, class: 'btn btn-primary mr-2' %>
            </li>
            <li>
              <%= link_to "会員一覧", admin_customers_path, class: 'btn btn-primary mr-2' %>
            </li>
            <li>
              <%= link_to "注文履歴一覧", admin_root_path, class: 'btn btn-primary mr-2' %>
            </li>
            <li>
              <%= link_to "ジャンル一覧", admin_genres_path, class: 'btn btn-primary mr-2' %>
            </li>
            <li>
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'btn btn-primary mr-1' %>
            </li>
          <% else %>
            <li>
              <%= link_to "About", public_homes_about_path, class: 'btn btn-primary mr-2' %>
            </li>
            <li>
              <%= link_to "商品一覧", public_products_path, class: 'btn btn-primary mr-2' %>
            </li>
            <li>
              <%= link_to "新規登録", new_customer_registration_path, class: 'btn btn-primary mr-2' %>
            </li>
            <li>
              <%= link_to "会員ログイン", customer_session_path, class: 'btn btn-primary mr-1' %>
            </li>
            <li>
              <%= link_to "管理者ログイン", admin_session_path, class: 'btn btn-primary mr-1' %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>